"""Modello Strategia Ads (AI-generated advertising strategy)

Ported from Ads AI (Node.js/SQLite) → Site Builder (FastAPI/PostgreSQL).
Created by the Architect module (Module 3).
Contains platform selection, funnel definition, budget allocation, ad copy, and KPI targets.
Strategies with confidence < 80 require manual approval (Supervision Panel).
"""

from sqlalchemy import Column, Integer, String, Float, Boolean, DateTime, ForeignKey, JSON, Index
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from app.core.database import Base


class AdStrategy(Base):
    __tablename__ = "ad_strategies"

    id = Column(Integer, primary_key=True, index=True)
    client_id = Column(Integer, ForeignKey("ad_clients.id", ondelete="CASCADE"), nullable=False)

    # Platform decision
    platform_primary = Column(String, nullable=False)    # 'google', 'meta', 'both'
    platform_secondary = Column(String, nullable=True)
    platform_reasoning = Column(String, nullable=True)

    # Funnel
    funnel_type = Column(String, nullable=True)  # 'direct_response', 'lead_gen'
    funnel_steps = Column(JSON, nullable=True)   # [{step, name, channel, objective, budgetPercent}]

    # Budget allocation
    budget_monthly = Column(Float, default=0)
    budget_daily = Column(Float, default=0)
    budget_split = Column(JSON, nullable=True)   # {google: 60, meta: 40}

    # Ad copy (generated by Architect)
    ad_copy_google = Column(JSON, nullable=True)  # {headlines, descriptions, path1, path2}
    ad_copy_meta = Column(JSON, nullable=True)    # [{variant, hook, body, cta}]

    # KPI targets
    kpi_targets = Column(JSON, nullable=True)  # {ctr, cpc, cpl, conversionRate, learningPhaseDays}

    # Approval flow (Supervision Panel)
    confidence = Column(Integer, default=70)           # 0-100
    requires_approval = Column(Boolean, default=True)
    status = Column(String, default="pending_approval")  # 'pending_approval', 'approved', 'rejected', 'active'
    approved_by = Column(Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True)
    approved_at = Column(DateTime(timezone=True), nullable=True)
    rejection_reason = Column(String, nullable=True)

    # Relazioni
    client = relationship("AdClient", back_populates="strategies")
    campaigns = relationship("AdCampaign", back_populates="strategy")

    # Timestamp
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    __table_args__ = (
        Index("ix_ad_strategies_client_id", "client_id"),
        Index("ix_ad_strategies_status", "status"),
    )
