"""Pydantic schemas for AI-generated site content validation."""

from .theme import ThemeSchema
from .sections import (
    HeroSection,
    AboutSection,
    ServicesSection,
    FeaturesSection,
    TestimonialsSection,
    GallerySection,
    ContactSection,
    CtaSection,
    FooterSection,
    NavSection,
    PricingSection,
    FaqSection,
    BlogSection,
    TeamSection,
    MenuSection,
    StatsSection,
    ProcessSection,
    ReservationSection,
    BookingSection,
    ComparisonSection,
    LogosSection,
    VideoSection,
    PortfolioSection,
    SocialProofSection,
    AppDownloadSection,
)
from .site import SectionData, SiteSchema
from .validators import (
    validate_section_content,
    fix_common_ai_errors,
    generate_prompt_schema,
    SECTION_SCHEMA_MAP,
)

__all__ = [
    "ThemeSchema",
    "HeroSection",
    "AboutSection",
    "ServicesSection",
    "FeaturesSection",
    "TestimonialsSection",
    "GallerySection",
    "ContactSection",
    "CtaSection",
    "FooterSection",
    "NavSection",
    "PricingSection",
    "FaqSection",
    "BlogSection",
    "TeamSection",
    "MenuSection",
    "StatsSection",
    "ProcessSection",
    "ReservationSection",
    "BookingSection",
    "ComparisonSection",
    "LogosSection",
    "VideoSection",
    "PortfolioSection",
    "SocialProofSection",
    "AppDownloadSection",
    "SectionData",
    "SiteSchema",
    "validate_section_content",
    "fix_common_ai_errors",
    "generate_prompt_schema",
    "SECTION_SCHEMA_MAP",
]
